# Generated by Django 5.1.4 on 2024-12-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(verbose_name='created')),
            ],
        ),
    ]
