# Generated by Django 5.1.4 on 2024-12-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/', verbose_name='Recordings'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
