# Generated by Django 5.1.4 on 2025-01-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_entry_audio_file_alter_entry_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
